// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

abstract class Native {
  Future<void> init(
      {required String tempDir,
      required String docDir,
      required String supportDir,
      required String cacheDir,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitConstMeta;

  Future<RenderResult?> renderMapOverlay(
      {required double zoom,
      required double left,
      required double top,
      required double right,
      required double bottom,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRenderMapOverlayConstMeta;

  Future<void> onLocationUpdate(
      {required double latitude,
      required double longitude,
      required int timestampMs,
      required double accuracy,
      double? altitude,
      double? speed,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOnLocationUpdateConstMeta;

  Future<List<RawDataFile>> listAllRawData({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kListAllRawDataConstMeta;

  Future<bool> getRawDataMode({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetRawDataModeConstMeta;

  Future<void> toggleRawDataMode({required bool enable, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kToggleRawDataModeConstMeta;

  Future<void> finalizeOngoingJourney({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kFinalizeOngoingJourneyConstMeta;
}

class RawDataFile {
  final String name;
  final String path;

  const RawDataFile({
    required this.name,
    required this.path,
  });
}

class RenderResult {
  final double left;
  final double top;
  final double right;
  final double bottom;
  final Uint8List data;

  const RenderResult({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
    required this.data,
  });
}
