// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.16.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RenderResult {
  final double left;
  final double top;
  final double right;
  final double bottom;
  final Uint8List data;

  const RenderResult({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
    required this.data,
  });

  @override
  int get hashCode =>
      left.hashCode ^
      top.hashCode ^
      right.hashCode ^
      bottom.hashCode ^
      data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderResult &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          top == other.top &&
          right == other.right &&
          bottom == other.bottom &&
          data == other.data;
}
