use crate::export_data::JourneyExport;
use crate::journey_vector::JourneyVector;
use anyhow::{Context, Ok, Result};
use auto_context::auto_context;
use kml::{Kml, KmlDocument, KmlWriter};
use std::collections::HashMap;
use std::io::{Seek, Write};

#[auto_context]
pub fn journey_vector_to_kml_file<T: Write + Seek>(
    journey_vector: &JourneyVector,
    writer: &mut T,
) -> Result<()> {
    let style = kml::types::Style {
        ..kml::types::Style::default()
    };

    let mut elements = vec![Kml::Style(style)];

    for track_segment in &journey_vector.track_segments {
        let mut coords = Vec::new();
        let mut gx_coords = Vec::new();
        track_segment.track_points.iter().for_each(|point| {
            coords.push(kml::types::Coord {
                x: point.longitude,
                y: point.latitude,
                z: None,
            });
            gx_coords.push(kml::types::Element {
                name: "gx:coord".to_owned(),
                content: Some(format!("{} {} {}", point.longitude, point.latitude, 0)),
                ..kml::types::Element::default()
            })
        });
        let geometry = kml::types::LineString {
            coords,
            tessellate: true,
            ..kml::types::LineString::default()
        };

        let placemark = kml::types::Placemark {
            name: Some("export".to_string()),
            children: vec![kml::types::Element {
                name: "gx:Track".to_owned(),
                content: None,
                children: gx_coords,
                ..kml::types::Element::default()
            }],
            geometry: Some(kml::types::Geometry::LineString(geometry)),
            ..kml::types::Placemark::default()
        };
        elements.push(kml::Kml::Placemark(placemark))
    }

    write_kml_document(
        "memolanes".to_owned(),
        "Generated by memolanes".to_owned(),
        elements,
        writer,
    )?;
    Ok(())
}

fn metadata_element(journey: &JourneyExport) -> kml::types::Element {
    let mut data = Vec::new();
    let mut add = |name: &str, value: String| {
        data.push(kml::types::Element {
            name: "Data".to_owned(),
            attrs: HashMap::from([("name".to_owned(), format!("memolanes:{name}"))]),
            children: vec![kml::types::Element {
                name: "value".to_owned(),
                content: Some(value),
                ..Default::default()
            }],
            ..Default::default()
        });
    };
    add("version", "1".to_owned());
    add("sourceJourneyId", journey.source_journey_id.clone());
    add("sourceRevision", journey.source_revision.clone());
    add("date", journey.journey_date.to_string());
    if let Some(value) = journey.start {
        add("start", value.to_rfc3339());
    }
    if let Some(value) = journey.end {
        add("end", value.to_rfc3339());
    }
    kml::types::Element {
        name: "ExtendedData".to_owned(),
        children: data,
        ..Default::default()
    }
}

fn timestamp_element(date: String) -> kml::types::Element {
    kml::types::Element {
        name: "TimeStamp".to_owned(),
        children: vec![kml::types::Element {
            name: "when".to_owned(),
            content: Some(date),
            ..Default::default()
        }],
        ..Default::default()
    }
}

#[auto_context]
pub(crate) fn journeys_to_kml_file<T: Write + Seek>(
    journeys: &[JourneyExport],
    writer: &mut T,
) -> Result<()> {
    if journeys.is_empty() {
        anyhow::bail!("No track segments");
    }
    let mut folders = Vec::new();
    for journey in journeys {
        let mut elements = vec![
            Kml::Element(timestamp_element(journey.journey_date.to_string())),
            Kml::Element(metadata_element(journey)),
        ];
        for segment in &journey.vector.track_segments {
            let coords = segment
                .track_points
                .iter()
                .map(|point| kml::types::Coord {
                    x: point.longitude,
                    y: point.latitude,
                    z: None,
                })
                .collect();
            let geometry = kml::types::LineString {
                coords,
                tessellate: true,
                ..Default::default()
            };
            elements.push(Kml::Placemark(kml::types::Placemark {
                name: Some("MemoLanes Track Segment".to_owned()),
                geometry: Some(kml::types::Geometry::LineString(geometry)),
                ..Default::default()
            }));
        }
        folders.push(Kml::Folder(kml::types::Folder {
            name: Some(format!("MemoLanes Journey {}", journey.journey_date)),
            elements,
            ..Default::default()
        }));
    }
    write_kml_document_with_elements(folders, writer)
}

#[auto_context]
fn write_kml_document<T: Write + Seek>(
    name: String,
    description: String,
    elements: Vec<Kml>,
    writer: &mut T,
) -> Result<()> {
    write_kml_document_with_elements(
        vec![Kml::Folder(kml::types::Folder {
            name: Some(name),
            description: Some(description),
            elements,
            ..Default::default()
        })],
        writer,
    )
}

fn write_kml_document_with_elements<T: Write + Seek>(
    elements: Vec<Kml>,
    writer: &mut T,
) -> Result<()> {
    let document = KmlDocument::<f64> {
        version: kml::KmlVersion::V22,
        attrs: HashMap::from([
            (
                "xmlns".to_owned(),
                "http://www.opengis.net/kml/2.2".to_owned(),
            ),
            (
                "xmlns:gx".to_owned(),
                "http://www.google.com/kml/ext/2.2".to_owned(),
            ),
            (
                "xmlns:kml".to_owned(),
                "http://www.opengis.net/kml/2.2".to_owned(),
            ),
            (
                "xmlns:atom".to_owned(),
                "http://www.w3.org/2005/Atom".to_owned(),
            ),
        ]),
        elements,
    };

    let mut writer = KmlWriter::<_, f64>::from_writer(writer);
    let kml = Kml::KmlDocument(document);
    writer.write(&kml)?;
    Ok(())
}
