use crate::journey_vector::JourneyVector;
use crate::raw_data::JourneyRawData;
use anyhow::{Context, Ok, Result};
use auto_context::auto_context;
use chrono::{DateTime, SecondsFormat, Utc};
use kml::{Kml, KmlDocument, KmlWriter};
use std::collections::HashMap;
use std::io::{Seek, Write};

#[auto_context]
pub fn journey_vector_to_kml_file<T: Write + Seek>(
    journey_vector: &JourneyVector,
    writer: &mut T,
) -> Result<()> {
    let style = kml::types::Style {
        ..kml::types::Style::default()
    };

    let mut elements = vec![Kml::Style(style)];

    for track_segment in &journey_vector.track_segments {
        let mut coords = Vec::new();
        let mut gx_coords = Vec::new();
        track_segment.track_points.iter().for_each(|point| {
            coords.push(kml::types::Coord {
                x: point.longitude,
                y: point.latitude,
                z: None,
            });
            gx_coords.push(kml::types::Element {
                name: "gx:coord".to_owned(),
                content: Some(format!("{} {} {}", point.longitude, point.latitude, 0)),
                ..kml::types::Element::default()
            })
        });
        let geometry = kml::types::LineString {
            coords,
            tessellate: true,
            ..kml::types::LineString::default()
        };

        let placemark = kml::types::Placemark {
            name: Some("export".to_string()),
            children: vec![kml::types::Element {
                name: "gx:Track".to_owned(),
                content: None,
                children: gx_coords,
                ..kml::types::Element::default()
            }],
            geometry: Some(kml::types::Geometry::LineString(geometry)),
            ..kml::types::Placemark::default()
        };
        elements.push(kml::Kml::Placemark(placemark))
    }

    write_kml_document(
        "memolanes".to_owned(),
        "Generated by memolanes".to_owned(),
        elements,
        writer,
    )?;
    Ok(())
}

#[auto_context]
pub fn journey_raw_data_to_kml_file<T: Write + Seek>(
    raw_data: &JourneyRawData,
    writer: &mut T,
) -> Result<()> {
    let coords = raw_data
        .points
        .iter()
        .map(|point| kml::types::Coord {
            x: point.raw_gps_point.point.longitude,
            y: point.raw_gps_point.point.latitude,
            z: point.raw_gps_point.altitude.map(f64::from),
        })
        .collect();
    let mut track_elements = Vec::with_capacity(raw_data.points.len() * 2);
    for point in &raw_data.points {
        let timestamp_ms = point
            .raw_gps_point
            .timestamp_ms
            .unwrap_or(point.received_timestamp_ms);
        if let Some(timestamp) = DateTime::<Utc>::from_timestamp_millis(timestamp_ms) {
            track_elements.push(kml::types::Element {
                name: "when".to_owned(),
                content: Some(timestamp.to_rfc3339_opts(SecondsFormat::Millis, true)),
                ..Default::default()
            });
        }
        track_elements.push(kml::types::Element {
            name: "gx:coord".to_owned(),
            content: Some(format!(
                "{} {} {}",
                point.raw_gps_point.point.longitude,
                point.raw_gps_point.point.latitude,
                point.raw_gps_point.altitude.unwrap_or_default()
            )),
            ..Default::default()
        });
    }

    let placemark = kml::types::Placemark {
        name: Some("MemoLanes Raw Data".to_owned()),
        children: vec![kml::types::Element {
            name: "gx:Track".to_owned(),
            children: track_elements,
            ..Default::default()
        }],
        geometry: Some(kml::types::Geometry::LineString(kml::types::LineString {
            coords,
            tessellate: true,
            ..Default::default()
        })),
        ..Default::default()
    };
    write_kml_document(
        "MemoLanes Raw Data".to_owned(),
        "Raw GPS data exported by MemoLanes".to_owned(),
        vec![Kml::Placemark(placemark)],
        writer,
    )
}

#[auto_context]
fn write_kml_document<T: Write + Seek>(
    name: String,
    description: String,
    elements: Vec<Kml>,
    writer: &mut T,
) -> Result<()> {
    let document = KmlDocument::<f64> {
        version: kml::KmlVersion::V22,
        attrs: HashMap::from([
            (
                "xmlns".to_owned(),
                "http://www.opengis.net/kml/2.2".to_owned(),
            ),
            (
                "xmlns:gx".to_owned(),
                "http://www.google.com/kml/ext/2.2".to_owned(),
            ),
            (
                "xmlns:kml".to_owned(),
                "http://www.opengis.net/kml/2.2".to_owned(),
            ),
            (
                "xmlns:atom".to_owned(),
                "http://www.w3.org/2005/Atom".to_owned(),
            ),
        ]),
        elements: vec![Kml::Folder(kml::types::Folder {
            name: Some(name),
            description: Some(description),
            elements,
            ..kml::types::Folder::default()
        })],
    };

    let mut writer = KmlWriter::<_, f64>::from_writer(writer);
    let kml = Kml::KmlDocument(document);
    writer.write(&kml)?;
    Ok(())
}
