// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.18.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../map_renderer.dart';
import '../storage.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> init(
        {required String tempDir,
        required String docDir,
        required String supportDir,
        required String cacheDir,
        dynamic hint}) =>
    RustLib.instance.api.init(
        tempDir: tempDir,
        docDir: docDir,
        supportDir: supportDir,
        cacheDir: cacheDir,
        hint: hint);

Future<RenderResult?> renderMapOverlay(
        {required double zoom,
        required double left,
        required double top,
        required double right,
        required double bottom,
        dynamic hint}) =>
    RustLib.instance.api.renderMapOverlay(
        zoom: zoom,
        left: left,
        top: top,
        right: right,
        bottom: bottom,
        hint: hint);

Future<void> onLocationUpdate(
        {required double latitude,
        required double longitude,
        required int timestampMs,
        required double accuracy,
        double? altitude,
        double? speed,
        dynamic hint}) =>
    RustLib.instance.api.onLocationUpdate(
        latitude: latitude,
        longitude: longitude,
        timestampMs: timestampMs,
        accuracy: accuracy,
        altitude: altitude,
        speed: speed,
        hint: hint);

Future<List<RawDataFile>> listAllRawData({dynamic hint}) =>
    RustLib.instance.api.listAllRawData(hint: hint);

Future<bool> getRawDataMode({dynamic hint}) =>
    RustLib.instance.api.getRawDataMode(hint: hint);

Future<void> toggleRawDataMode({required bool enable, dynamic hint}) =>
    RustLib.instance.api.toggleRawDataMode(enable: enable, hint: hint);

Future<void> finalizeOngoingJourney({dynamic hint}) =>
    RustLib.instance.api.finalizeOngoingJourney(hint: hint);
