use std::env;
use std::path::Path;
use std::process::Command;
use std::{fs, io::Write};

fn check_and_create_file(file_path: &str, warning_message: &str, content: &str) {
    println!("cargo:rerun-if-changed={file_path}");
    if fs::metadata(file_path).is_err() {
        let mut file = fs::File::create(file_path).unwrap();
        file.write_all(content.as_bytes())
            .expect("failed to write to dummy file");

        file.flush().expect("failed to flush dummy file");
        println!("cargo:warning={warning_message}");
    }
}

fn load_env_file() {
    const ENV_FILE: &str = ".env";

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("Failed to get CARGO_MANIFEST_DIR");
    let env_path = Path::new(&manifest_dir).join(format!("../{ENV_FILE}"));

    println!("cargo:rerun-if-changed={}", env_path.display());

    if let Ok(env_content) = fs::read_to_string(&env_path) {
        for l in env_content.lines() {
            // Skip comments and empty lines
            if l.starts_with('#') || l.trim().is_empty() {
                continue;
            }
            let v: Vec<_> = l.split('=').collect();
            if v.len() == 2 {
                let key = v[0].trim();
                let value = v[1].trim();
                env::set_var(key, value);
            }
        }
    }
}

/// Compile each bundled `assets/geo/geo_data_<id>.bin`'s provenance hash in, so
/// the runtime can spot a stale installed copy without reading the asset.
///
/// A missing bin is fatal under `CI` but only a warning locally: a contributor
/// who is not touching geo should not have to fetch Natural Earth to build. CI
/// always has the bins (`rasterize-geo` is ungated there), so the
/// `geo_bins_present` cfg emitted here gates the real-asset tests off on a bare
/// clone without ever narrowing what CI runs.
fn generate_geo_provenance() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("Failed to get CARGO_MANIFEST_DIR");
    let assets = Path::new(&manifest_dir).join("../assets/geo");
    println!("cargo:rustc-check-cfg=cfg(geo_bins_present)");
    println!("cargo:rerun-if-env-changed=CI");

    let mut arms = String::new();
    let mut missing = Vec::new();
    for worldview in geo_data_format::Worldview::ALL {
        let id = worldview.spec().id;
        let bin = assets.join(format!("geo_data_{id}.bin"));
        println!("cargo:rerun-if-changed={}", bin.display());
        let arm = match geo_data_format::read_provenance_hash(&bin)
            .unwrap_or_else(|e| panic!("reading {}: {e:#}", bin.display()))
        {
            Some(hash) => format!("Some({hash:?})"),
            None => {
                missing.push(bin.display().to_string());
                "None".to_owned()
            }
        };
        arms.push_str(&format!(
            "        geo_data_format::Worldview::{worldview:?} => {arm},\n"
        ));
    }

    if missing.is_empty() {
        println!("cargo:rustc-cfg=geo_bins_present");
    } else if env::var_os("CI").is_some() {
        panic!(
            "geo assets absent under CI: {}. `just rasterize-geo` must run before this crate is \
             built, or the binary would ship with no provenance hash.",
            missing.join(", ")
        );
    } else {
        println!(
            "cargo:warning=geo assets absent ({}) - building without provenance hashes. Geo data \
             cannot be activated and the real-asset tests are skipped. Run `just rasterize-geo`.",
            missing.join(", ")
        );
    }

    let content = format!(
        "// This file is auto generated by `build.rs`
#![cfg_attr(rustfmt, rustfmt::skip)]

/// Provenance hash of each bundled `assets/geo/geo_data_<id>.bin`, read from its
/// header at build time so the runtime can recognize a stale installed copy
/// without loading the asset. `None` when the asset was absent at build time.
pub const fn bundled_provenance_hash(worldview: geo_data_format::Worldview) -> Option<[u8; 32]> {{
    match worldview {{
{arms}    }}
}}
"
    );

    let path = "src/geo_provenance.rs";
    if fs::read_to_string(path).map_or(true, |current| current != content) {
        fs::write(path, content).unwrap();
    }
}

fn main() {
    load_env_file();

    // Do not track the whole .git directory: it can contain Unix sockets.
    println!("cargo:rerun-if-changed=../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../.git/logs/HEAD");
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .expect("Failed to execute command");
    let git_hash = std::str::from_utf8(&output.stdout).unwrap().trim();

    println!("cargo:rerun-if-env-changed=MAPBOX-ACCESS-TOKEN");
    let mapbox_access_token = match env::var("MAPBOX-ACCESS-TOKEN").ok() {
        Some(token) => format!("Some(\"{token}\")"),
        None => "None".to_string(),
    };

    let build_info = format!(
        "// This file is auto generated by `build.rs`
pub const SHORT_COMMIT_HASH: &str = \"{git_hash}\";
pub const MAPBOX_ACCESS_TOKEN: Option<&str> = {mapbox_access_token};
"
    );
    let build_info_path = "src/build_info.rs";
    let build_info_changed =
        fs::read_to_string(build_info_path).map_or(true, |current| current != build_info);
    if build_info_changed {
        fs::write(build_info_path, build_info).unwrap();
    }

    generate_geo_provenance();

    // Generate protobuf files
    println!("cargo:rerun-if-changed=src/protos/journey.proto");
    println!("cargo:rerun-if-changed=src/protos/archive.proto");
    println!("cargo:rerun-if-changed=src/protos/raw_data.proto");
    protobuf_codegen::Codegen::new()
        .pure()
        .out_dir("src/protos")
        .include("src/protos")
        .input("src/protos/journey.proto")
        .input("src/protos/archive.proto")
        .input("src/protos/raw_data.proto")
        .run_from_script();

    // Check and create necessary dependency files
    check_and_create_file(
        "src/frb_generated.rs",
        "`frb_generated.rs` is not found, generating a dummy file. If you are working on flutter, you need to run `flutter_rust_bridge_codegen generate` to get a real one.",
        "pub struct StreamSink<T> { _phantom: std::marker::PhantomData<T> }\nimpl<T> StreamSink<T> {\n    pub fn add(&mut self, _message: T) -> Result<(), ()> {\n        Ok(())\n    }\n}"
    );
}
