use std::env;
use std::path::Path;
use std::process::Command;
use std::{fs, io::Write};

fn check_and_create_file(file_path: &str, warning_message: &str, content: &str) {
    println!("cargo:rerun-if-changed={file_path}");
    if fs::metadata(file_path).is_err() {
        let mut file = fs::File::create(file_path).unwrap();
        file.write_all(content.as_bytes())
            .expect("failed to write to dummy file");

        file.flush().expect("failed to flush dummy file");
        println!("cargo:warning={warning_message}");
    }
}

fn load_env_file() {
    const ENV_FILE: &str = ".env";

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("Failed to get CARGO_MANIFEST_DIR");
    let env_path = Path::new(&manifest_dir).join(format!("../{ENV_FILE}"));

    println!("cargo:rerun-if-changed={}", env_path.display());

    if let Ok(env_content) = fs::read_to_string(&env_path) {
        for l in env_content.lines() {
            // Skip comments and empty lines
            if l.starts_with('#') || l.trim().is_empty() {
                continue;
            }
            let v: Vec<_> = l.split('=').collect();
            if v.len() == 2 {
                let key = v[0].trim();
                let value = v[1].trim();
                env::set_var(key, value);
            }
        }
    }
}

fn main() {
    load_env_file();

    // Trigger rebuild if .git directory changes
    // There are articles on internet suggest `.git/HEAD` is enough, which I
    // doubt.
    println!("cargo:rerun-if-changed=../../.git");
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .expect("Failed to execute command");
    let git_hash = std::str::from_utf8(&output.stdout).unwrap().trim();

    println!("cargo:rerun-if-env-changed=MAPBOX-ACCESS-TOKEN");
    let mapbox_access_token = match env::var("MAPBOX-ACCESS-TOKEN").ok() {
        Some(token) => format!("Some(\"{token}\")"),
        None => "None".to_string(),
    };

    std::fs::write(
        "src/build_info.rs",
        format!(
            "// This file is auto generated by `build.rs`
pub const SHORT_COMMIT_HASH: &str = \"{git_hash}\";
pub const MAPBOX_ACCESS_TOKEN: Option<&str> = {mapbox_access_token};
"
        ),
    )
    .unwrap();

    // Generate protobuf files
    println!("cargo:rerun-if-changed=src/protos/journey.proto");
    println!("cargo:rerun-if-changed=src/protos/archive.proto");
    protobuf_codegen::Codegen::new()
        .pure()
        .out_dir("src/protos")
        .include("src/protos")
        .input("src/protos/journey.proto")
        .input("src/protos/archive.proto")
        .run_from_script();

    // Check and create necessary dependency files
    check_and_create_file(
        "src/frb_generated.rs",
        "`frb_generated.rs` is not found, generating a dummy file. If you are working on flutter, you need to run `flutter_rust_bridge_codegen generate` to get a real one.",
        "pub struct StreamSink<T> { _phantom: std::marker::PhantomData<T> }\nimpl<T> StreamSink<T> {\n    pub fn add(&mut self, _message: T) -> Result<(), ()> {\n        Ok(())\n    }\n}"
    );
}
