//! Smoke test over a *real* rasterized worldview asset: it validates the whole
//! rasterizer → packed format → `GeoLookup` pipeline (including the x-major cell
//! alignment) against actual country geometry. The asset is gitignored and
//! generated by `just rasterize-geo`, so the test skips when it is absent (e.g.
//! on a clean CI without the data step); the committed correctness coverage is
//! the synthetic `geo_lookup` test.

use std::path::Path;

use memolanes_core::{
    geo::{GeoIndex, GeoLookup},
    journey_bitmap::{BlockKey, TileKey},
};

/// Web-mercator (lng, lat) → (tile, block) on the 65 536-block grid — the same
/// projection the rasterizer used, so the lookup is self-consistent with the asset.
fn block_of(lng: f64, lat: f64) -> (TileKey, BlockKey) {
    let n = 65536.0;
    let lat_rad = lat.to_radians();
    let x = (lng + 180.0) / 360.0 * n;
    let y = (1.0 - ((lat_rad.tan() + 1.0 / lat_rad.cos()).ln() / std::f64::consts::PI)) / 2.0 * n;
    let (bx, by) = (x as u32, y as u32);
    (
        TileKey::new((bx / 128) as u16, (by / 128) as u16),
        BlockKey::from_x_y((bx % 128) as u8, (by % 128) as u8),
    )
}

#[test]
fn iso_asset_resolves_known_country_locations() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../assets/geo/geo_data_iso.bin");
    if !path.exists() {
        eprintln!(
            "skipping: {} absent — run `just rasterize-geo` to generate it",
            path.display()
        );
        return;
    }
    let geo = GeoIndex::from_bytes(&std::fs::read(&path).unwrap()).unwrap();

    // City centers, well inside their countries (ADM0_A3 iso codes).
    for (lng, lat, iso) in [
        (2.3522, 48.8566, "FRA"),    // Paris
        (139.6917, 35.6895, "JPN"),  // Tokyo
        (-99.1332, 19.4326, "MEX"),  // Mexico City
        (151.2093, -33.8688, "AUS"), // Sydney
    ] {
        let (tile, block) = block_of(lng, lat);
        let id = geo
            .entity_of_block(tile, block)
            .unwrap_or_else(|| panic!("{iso}: resolved to ocean at ({lng}, {lat})"));
        assert_eq!(
            geo.entity(id).unwrap().iso_code,
            iso,
            "lookup at ({lng}, {lat})"
        );
    }
}
