name: Rust CI

on: 
  push:
    paths:
      - '.github/workflows/rust_ci.yml'
      - 'app/rust/**'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/rust_ci.yml'
      - 'app/rust/**'
    branches: 
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: app/

    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "app/rust/"
          
      # Rust
      - name: Cargo Check
        working-directory: app/rust
        run: cargo check
      - name: Check Rust format
        working-directory: app/rust
        run: cargo fmt --all -- --check
      - name: Rust code analysis
        working-directory: app/rust
        run: cargo clippy -- -D warnings
      - name: Run Rust tests
        working-directory: app/rust
        run: cargo test -- --nocapture
